Tweak version_check_modules script to handle packages that aren't installed

diff --git a/bin/version_check_modules b/bin/version_check_modules
--- a/bin/version_check_modules
+++ b/bin/version_check_modules
@@ -122,29 +122,30 @@ for application in ${application_list}; do
         # echo "Latest ${application} installed is ${current_version}"
 
 	if [ -z "${current_version}" ]; then
-		echo "Unable to get current version for ${application}. Not installed?"
-		exit 1
+		echo "${application} not installed"
+		#echo "Unable to get current version for ${application}. Not installed?"
+		#exit 1
+	else
+	  check=$(${uscan} --package ${application} --watchfile ${application}/uscan/watch --upstream-version ${current_version} ${uscan_args})
+
+	  # In some cases the version on our repos may be newer
+          if grep -q "remote site does not even have current version" <<<$check;
+          then
+                  log "${application} ${current_version} (${repo}): Newer than most recent on site"
+		  log "${application} ${current_version} (${repo}): Up to date"
+          else
+		  if [ -n "${check}" ]; then
+			  if [ -n "${report_upstream_version}" ]; then
+				  echo ${check} | cut -f1 -d, | awk '{print $13}'
+				  exit 0
+			  fi
+			  [ "${output_updates}" == "true" ] && echo -n "${application} "
+			  log ${check}
+		  else
+			  log "${application} ${current_version} (${repo}): Up to date"
+		  fi
+          fi
 	fi
-
-	check=$(${uscan} --package ${application} --watchfile ${application}/uscan/watch --upstream-version ${current_version} ${uscan_args})
-
-	# In some cases the version on our repos may be newer
-        if grep -q "remote site does not even have current version" <<<$check;
-        then
-                log "${application} ${current_version} (${repo}): Newer than most recent on site"
-		log "${application} ${current_version} (${repo}): Up to date"
-        else
-		if [ -n "${check}" ]; then
-			if [ -n "${report_upstream_version}" ]; then
-				echo ${check} | cut -f1 -d, | awk '{print $13}'
-				exit 0
-			fi
-			[ "${output_updates}" == "true" ] && echo -n "${application} "
-			log ${check}
-		else
-			log "${application} ${current_version} (${repo}): Up to date"
-		fi
-        fi
 done 
 
 exit 0
