Update medaka build to use pip3

diff --git a/apps/medaka/SPEC/build b/apps/medaka/SPEC/build
--- a/apps/medaka/SPEC/build
+++ b/apps/medaka/SPEC/build
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -e
 
 # Script to auto build and install medaka. Just provide the version
 
@@ -24,26 +25,25 @@ echo "Building ${APP} ${VERSION} on ${DATE}"
 
 # Create install directory
 mkdir -p /opt/bioit/${APP}/${VERSION}/bin
-# Generate Singularity def file (use micromamba option)
-#export APPTAINER_TMPDIR=/opt/bioit/${APP}/${VERSION}/tmp
-#export APPTAINER_CACHEDIR=/opt/bioit/${APP}/${VERSION}/cache
-#mkdir -p $APPTAINER_TMPDIR
-#mkdir -p $APPTAINER_CACHEDIR
-#setfacl -b $APPTAINER_TMPDIR
-${HOME}/bioit/bin/create_singularity_conda_env.py3 -u -a ${APP} -v ${VERSION} -l /opt/bioit/${APP}/${VERSION}
-# Build container
-apptainer build --fakeroot /opt/bioit/${APP}/${VERSION}/${APP}_${VERSION}.sif /opt/bioit/${APP}/${VERSION}/Singularity
+# Build container def from template by adding version in
+sed -e "s%VERSION%${VERSION}%g" ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}.def_template > ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
+# build container
+apptainer build --fakeroot /opt/bioit/${APP}/${VERSION}/${APP}_${VERSION}.sif ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
+# remove the def file to clean up
+rm ${HOME}/bioit/apps/${APP}/SPEC/ubuntu_${APP}_${VERSION}.def
 # Create version specific template
 sed -e "s%APPVER%${APP}_${VERSION}%g" ${HOME}/bioit/bin/bin_template > ${APP}_bin_template
 sed -i "s%APPNAME%${APP}%g" ${APP}_bin_template
 sed -i "s%VERSION%${VERSION}%g" ${APP}_bin_template
 sed -i "s%BINDS%/raid%g" ${APP}_bin_template
 #sed -i "s%BINDS%/raid,/active,/archive,/data,/databases,/deepgene,/dunninga,/gbs_pine,/scratch,/sequencing,/treestem%g" ${APP}_bin_template
-sed -i "s%EXEC%micromamba run -p /opt/conda/envs/${APP}_${VERSION}_singularity%g" ${APP}_bin_template
+#sed -i "s%EXEC%micromamba run -p /opt/conda/envs/${APP}_${VERSION}_singularity%g" ${APP}_bin_template
+sed -i "s%EXEC %%g" ${APP}_bin_template
 
 # Create scripts to run each binary in container
 cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka
 cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka_consensus
+cat ${APP}_bin_template > /opt/bioit/${APP}/${VERSION}/bin/medaka_haploid_variant
 
 # Make all scripts executable
 chmod a+x /opt/bioit/${APP}/${VERSION}/bin/*
@@ -55,6 +55,9 @@ echo "#%Module 1.0
 #
 #  ${APP} module for use with 'environment-modules' package:
 #
+module load samtools/1.18
+module load minimap2/2.26
+module load htslib/1.18
 prepend-path  PATH              /opt/bioit/${APP}/${VERSION}/bin" > /opt/bioit/modulefiles/${APP}/${VERSION}
 echo "Writing module .version to set default"
 echo "#%Module1.0
